name: Deploy Leptos SPA to GitHub Pages

on:
  push:
    branches: [main] # or your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Leptos CLI
        run: cargo install cargo-leptos

      - name: Build Leptos SPA
        run: cargo leptos build --release --public-url /portfolio-rs

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
